/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "js-code-analyzer",
  "name": "Code Atlas",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "Which function is the most complex and why?",
      "does": "Reads the metrics and explains the hotspot."
    },
    {
      "say": "Write unit tests for the parse function",
      "does": "Generates tests for that function."
    },
    {
      "say": "Refactor the longest function into smaller ones",
      "does": "Proposes a refactor you can compare and copy."
    }
  ]
};
